# Generated by Django 4.0.4 on 2022-07-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('tag', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='QAPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('tag', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=6)),
                ('content', models.TextField()),
                ('tag', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=30)),
                ('star', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_pwd', models.CharField(max_length=20)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=10)),
                ('user_university', models.CharField(max_length=30)),
                ('user_e_mail', models.CharField(max_length=40)),
                ('user_phonenumber', models.CharField(max_length=15)),
                ('user_shop', models.CharField(default=' ', max_length=15)),
                ('user_money', models.IntegerField(default=0)),
            ],
        ),
    ]
